[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
backhand = "0.20.0"
futures = "0.3.31"
ring = "0.17.8"
rustls = "0.23.21"
rustls-pemfile = "2.2.0"
tokio = { version = "1.43.0", features = ["full"] }
tokio-rustls = "0.26.1"
