/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MachinesRouteImport } from './routes/machines'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MachinesMachineIdRouteImport } from './routes/machines_.$machineId'

const MachinesRoute = MachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesMachineIdRoute = MachinesMachineIdRouteImport.update({
  id: '/machines_/$machineId',
  path: '/machines/$machineId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/machines': typeof MachinesRoute
  '/machines/$machineId': typeof MachinesMachineIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/machines': typeof MachinesRoute
  '/machines/$machineId': typeof MachinesMachineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/machines': typeof MachinesRoute
  '/machines_/$machineId': typeof MachinesMachineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/machines' | '/machines/$machineId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/machines' | '/machines/$machineId'
  id: '__root__' | '/' | '/machines' | '/machines_/$machineId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MachinesRoute: typeof MachinesRoute
  MachinesMachineIdRoute: typeof MachinesMachineIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/machines': {
      id: '/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines_/$machineId': {
      id: '/machines_/$machineId'
      path: '/machines/$machineId'
      fullPath: '/machines/$machineId'
      preLoaderRoute: typeof MachinesMachineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MachinesRoute: MachinesRoute,
  MachinesMachineIdRoute: MachinesMachineIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
